#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

if [ ! -f /usr/local/bin/brew ]; then
	# Install brew (this also install Xcode command line tools)
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	brew doctor
fi

if [ ! -f shell/main.sh ]; then
	# We aren't running from inside the dotfiles directory

	# Assume we start in user's home directory
	cd ~/
	
	# Grab dotfiles directory
	git clone --recursive https://www.github.com/jom/dotfiles.git

	# Run main setup file
	cd dotfiles
fi

sh shell/main.sh

if [ "$1" == "--work" ]; then
	shell/work.sh
fi
